name: macos-x86
on: [push, pull_request]
jobs:
  linux:
    name: macos-x86
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: compile x86 on macos
        run: |
          brew install gnu-getopt > /dev/null
          echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> /Users/runner/.bash_profile
          echo 'export FLAGS_GETOPT_CMD="$(brew --prefix gnu-getopt)/bin/getopt"' >> /Users/runner/.bash_profile
          source /Users/runner/.bash_profile
          ./install.sh --target=macos-x86_64
